#!/bin/bash

# update this to move to later versions of this repo:
# https://github.com/bazelbuild/bazel

ORIGINAL_PWD=$PWD
TMPDIR="${TMPDIR:-/tmp}"
RND_UID=$(date "+%s")

set -e

CMD_LOC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $CMD_LOC

findWorkspace() {
  OLD_PWD=$PWD
  if [ ! -f WORKSPACE ]; then
    cd ..
    if [ "$PWD" == "$OLD_PWD" ]; then
      echo "Didn't find the workspace"
      exit 1
    fi

    findWorkspace
  fi
}

findWorkspace

REPO_ROOT=$PWD
cd $ORIGINAL_PWD


BAZEL_RC_PATH=${TMPDIR}/bazel_bazel_rc_${RND_UID}
cat $REPO_ROOT/tools/default_bazel_rc > $BAZEL_RC_PATH

if [ -f /etc/bazelrc ]; then
  cat /etc/bazelrc >> $BAZEL_RC_PATH
fi

if [ -f $HOME/.bazelrc ]; then
  cat $HOME/.bazelrc >> $BAZEL_RC_PATH
fi

if [ -f $REPO_ROOT/.bazelrc ]; then
  cat $REPO_ROOT/.bazelrc >> $BAZEL_RC_PATH
fi


export GITSHA=$(cat $REPO_ROOT/WORKSPACE | egrep '^BAZEL_VERSION\s*=\s*' | sed -e 's/.*=//g' -e 's/ //g' -e 's/"//g')

if [ -z "$BAZEL_BIN_LOC" ]; then
  BAZEL_BIN_LOC=~/.bazel
fi

mkdir -p $BAZEL_BIN_LOC
export BAZEL_EXEC_PATH=$BAZEL_BIN_LOC/$GITSHA

if [ -f "$BAZEL_EXEC_PATH" ]; then
  exec $BAZEL_EXEC_PATH --bazelrc $BAZEL_RC_PATH "$@"
fi

export BUILD_DIR=${TMPDIR}/bazel_b_${RND_UID}
mkdir -p $BUILD_DIR

( # Opens a subshell
  set -e
  echo "Building Bazel, this will take ~2mins"
  GITHUB_URL=https://github.com/bazelbuild/bazel/archive/$GITSHA.zip
  cd $BUILD_DIR
  echo "Fetching bazel"
  curl -s -O -L $GITHUB_URL
  echo "Fetch complete, unpacking and building"
  unzip $GITSHA.zip > /dev/null
  cd bazel-$GITSHA

  export SYS_BAZEL_PATH=$(which bazel)
  RET=-1
  if [ -n "$SYS_BAZEL_PATH" ]; then
    set +e
    (
      set -e
      echo "Found system bazel, will try use to build bazel with"
      ./compile.sh compile $SYS_BAZEL_PATH > /dev/null
      exit $?
    )
    RET=$?
    set -e
  fi
  echo $RET

  if [ ! $RET -eq 0 ]; then
    echo "Couldn't compile with system bazel, trying self-bootstrapping."
    ./compile.sh > /dev/null
  fi

  mv output/bazel $BAZEL_EXEC_PATH
)
rm -rf $BUILD_DIR

cd $ORIGINAL_PWD


exec $BAZEL_EXEC_PATH --bazelrc $BAZEL_RC_PATH "$@"
